[package]
name = "pulsebeam-rtc"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
dcsctp = "=0.1.14"
is = { git = "https://github.com/PulseBeamDev/str0m.git", branch = "patch/0.23.1" }
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa", "std"] }
rcgen = { version = "0.14.7", default-features = false, features = ["aws_lc_rs"] }
sha2.workspace = true
str0m = { git = "https://github.com/PulseBeamDev/str0m.git", branch = "patch/0.23.1", default-features = false, features = ["aws-lc-rs"] }
thiserror.workspace = true

[dev-dependencies]
proptest = "1.11.0"
str0m-reference = { package = "str0m", version = "=0.23.1", default-features = false, features = ["aws-lc-rs"] }

[lints]
workspace = true
