set shell := ["bash", "-euc"]

test-fast:
    cargo test -p pulsebeam-rtc

test-slow:
    scripts/run-rfc8888-peer.sh
    scripts/run-browser-matrix.sh --platform linux-x86_64

bench *args:
    cargo bench -p pulsebeam-rtc --bench scaling -- {{ args }}
