// This file is @generated by prost-build.
/// One sequenced data frame sent from publisher to subscriber(s).
/// Carried on the raw data topic (e.g. "game-sync").
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArqFrame {
    /// Monotonically increasing per (publisher, topic) instance.
    /// u64 avoids wraparound for any realistic session length.
    #[prost(uint64, tag = "1")]
    pub seq: u64,
    /// Informational only: set when this is a retransmit of a previously sent
    /// frame.  Receivers dedup by seq regardless of this flag.
    #[prost(bool, tag = "2")]
    pub is_retransmit: bool,
    /// Opaque application payload.
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// Cumulative + selective acknowledgement sent from subscriber to publisher.
/// Carried on the sibling ack topic (e.g. "game-sync_ack").
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArqAck {
    /// Acking subscriber's participant id (fixed 29-char ASCII "pa_…" string),
    /// used by the publisher to demux acks from multiple subscribers sharing one
    /// ack topic and to maintain per-subscriber retransmit watermarks.
    #[prost(string, tag = "1")]
    pub subscriber_id: ::prost::alloc::string::String,
    /// next_expected: exclusive upper bound of contiguous delivery.
    /// "I have delivered every seq < next_expected and am waiting for this one."
    /// A value of 0 means nothing has been delivered yet — no eviction triggered.
    #[prost(uint64, tag = "2")]
    pub next_expected: u64,
    /// Sparse list of sequence numbers in [next_expected, max_buffered) that
    /// have been received out-of-order but are not yet deliverable (waiting for
    /// earlier gaps to close).  Capped at 32 entries to bound ack size.
    #[prost(uint64, repeated, tag = "3")]
    pub missing: ::prost::alloc::vec::Vec<u64>,
}
