// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DesiredSubscription {
    #[prost(string, tag = "1")]
    pub mid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub remote_track_id: ::prost::alloc::string::String,
}
/// Client declares what it wants subscribed
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientState {
    /// Full list of desired subscriptions
    #[prost(message, repeated, tag = "1")]
    pub subscriptions: ::prost::alloc::vec::Vec<DesiredSubscription>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrackInfo {
    #[prost(string, tag = "1")]
    pub track_id: ::prost::alloc::string::String,
    #[prost(enumeration = "TrackKind", tag = "2")]
    pub kind: i32,
    #[prost(string, tag = "3")]
    pub participant_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActiveSubscription {
    #[prost(string, tag = "1")]
    pub mid: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub track: ::core::option::Option<TrackInfo>,
}
/// Server reports current reality
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerState {
    /// All tracks available to subscribe
    #[prost(message, repeated, tag = "1")]
    pub available_tracks: ::prost::alloc::vec::Vec<TrackInfo>,
    /// Your actual active subscriptions
    #[prost(message, repeated, tag = "2")]
    pub subscriptions: ::prost::alloc::vec::Vec<ActiveSubscription>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TrackKind {
    Unspecified = 0,
    Video = 1,
    Audio = 2,
}
impl TrackKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRACK_KIND_UNSPECIFIED",
            Self::Video => "VIDEO",
            Self::Audio => "AUDIO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRACK_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "VIDEO" => Some(Self::Video),
            "AUDIO" => Some(Self::Audio),
            _ => None,
        }
    }
}
