// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DesiredSubscription {
    #[prost(string, tag = "1")]
    pub mid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub remote_track_id: ::prost::alloc::string::String,
}
/// Client declares what it wants subscribed (always full state)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientState {
    #[prost(message, repeated, tag = "1")]
    pub subscriptions: ::prost::alloc::vec::Vec<DesiredSubscription>,
}
/// Empty - signals client wants full snapshot
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientRequestSync {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(oneof = "client_message::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<client_message::Payload>,
}
/// Nested message and enum types in `ClientMessage`.
pub mod client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        State(super::ClientState),
        #[prost(message, tag = "2")]
        RequestSync(super::ClientRequestSync),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrackInfo {
    #[prost(string, tag = "1")]
    pub track_id: ::prost::alloc::string::String,
    #[prost(enumeration = "TrackKind", tag = "2")]
    pub kind: i32,
    #[prost(string, tag = "3")]
    pub participant_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActiveSubscription {
    #[prost(string, tag = "1")]
    pub mid: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub track: ::core::option::Option<TrackInfo>,
}
/// Delta: incremental changes (can contain track AND subscription changes atomically)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStateDelta {
    #[prost(message, repeated, tag = "1")]
    pub tracks_added: ::prost::alloc::vec::Vec<TrackInfo>,
    /// track_ids
    #[prost(string, repeated, tag = "2")]
    pub tracks_removed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub subscriptions_added: ::prost::alloc::vec::Vec<ActiveSubscription>,
    /// mids
    #[prost(string, repeated, tag = "4")]
    pub subscriptions_removed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Snapshot: full state (on connect, reconnect, or resync request)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStateSnapshot {
    #[prost(message, repeated, tag = "1")]
    pub available_tracks: ::prost::alloc::vec::Vec<TrackInfo>,
    #[prost(message, repeated, tag = "2")]
    pub subscriptions: ::prost::alloc::vec::Vec<ActiveSubscription>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMessage {
    #[prost(oneof = "server_message::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<server_message::Payload>,
}
/// Nested message and enum types in `ServerMessage`.
pub mod server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        /// Initialization and recovery
        #[prost(message, tag = "1")]
        Snapshot(super::ServerStateSnapshot),
        /// Normal operation
        #[prost(message, tag = "2")]
        Delta(super::ServerStateDelta),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TrackKind {
    Unspecified = 0,
    Video = 1,
    Audio = 2,
}
impl TrackKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRACK_KIND_UNSPECIFIED",
            Self::Video => "VIDEO",
            Self::Audio => "AUDIO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRACK_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "VIDEO" => Some(Self::Video),
            "AUDIO" => Some(Self::Audio),
            _ => None,
        }
    }
}
