// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrackInfo {
    #[prost(string, tag = "1")]
    pub track_id: ::prost::alloc::string::String,
    #[prost(enumeration = "TrackKind", tag = "2")]
    pub kind: i32,
    #[prost(string, tag = "3")]
    pub participant_id: ::prost::alloc::string::String,
}
/// Reserved for future parameters (e.g., spatial_layer, max_fps, priority).
/// uint32 quality_layer = 1;
/// uint32 priority = 2;
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscriptionConfiguration {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DesiredSubscription {
    #[prost(string, tag = "1")]
    pub mid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub remote_track_id: ::prost::alloc::string::String,
    /// Optional configuration for this specific subscription.
    #[prost(message, optional, tag = "3")]
    pub config: ::core::option::Option<SubscriptionConfiguration>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DesiredSubscriptions {
    #[prost(message, repeated, tag = "1")]
    pub subscriptions: ::prost::alloc::vec::Vec<DesiredSubscription>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestSync {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(oneof = "client_message::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<client_message::Payload>,
}
/// Nested message and enum types in `ClientMessage`.
pub mod client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        DesiredState(super::DesiredSubscriptions),
        #[prost(message, tag = "2")]
        RequestSync(super::RequestSync),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActiveSubscription {
    #[prost(string, tag = "1")]
    pub mid: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub track: ::core::option::Option<TrackInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AvailableTracksSnapshot {
    #[prost(message, repeated, tag = "1")]
    pub tracks: ::prost::alloc::vec::Vec<TrackInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveSubscriptionsSnapshot {
    #[prost(message, repeated, tag = "1")]
    pub subscriptions: ::prost::alloc::vec::Vec<ActiveSubscription>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignalError {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Independent fields. Presence implies a full replacement of that state.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMessage {
    #[prost(message, optional, tag = "1")]
    pub available_tracks: ::core::option::Option<AvailableTracksSnapshot>,
    #[prost(message, optional, tag = "2")]
    pub active_subscriptions: ::core::option::Option<ActiveSubscriptionsSnapshot>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<SignalError>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TrackKind {
    Unspecified = 0,
    Video = 1,
    Audio = 2,
}
impl TrackKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRACK_KIND_UNSPECIFIED",
            Self::Video => "VIDEO",
            Self::Audio => "AUDIO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRACK_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "VIDEO" => Some(Self::Video),
            "AUDIO" => Some(Self::Audio),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SubscriptionStatus {
    StatusUnspecified = 0,
    Active = 1,
    /// E.g., user muted locally
    Paused = 2,
    /// E.g., insufficient bandwidth
    Degraded = 3,
}
impl SubscriptionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StatusUnspecified => "STATUS_UNSPECIFIED",
            Self::Active => "ACTIVE",
            Self::Paused => "PAUSED",
            Self::Degraded => "DEGRADED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNSPECIFIED" => Some(Self::StatusUnspecified),
            "ACTIVE" => Some(Self::Active),
            "PAUSED" => Some(Self::Paused),
            "DEGRADED" => Some(Self::Degraded),
            _ => None,
        }
    }
}
