import { useEffect, useMemo, useRef, useState } from "react";
import type React from "react";
import { AgentProvider, createAgent, useAgent } from "@pulsebeam/react";
import type { RemoteTrack } from "@pulsebeam/react";
import { Button, Input } from "./ui";
import { LocalVideo } from "./LocalVideo";
import { desiredState } from "@/lib/model";
import { useTopics } from "@/hooks/topics";

const stop = (stream: MediaStream | null) => stream?.getTracks().forEach((track) => track.stop());
export function Room({ roomId, endpoint, stream, onLeave }: { roomId: string; endpoint: string; stream: MediaStream; onLeave(): void }) {
  const agent = useMemo(() => createAgent({ endpoint, roomId, topology: { localVideo: ["camera", "screen"], localAudio: ["microphone"], remoteVideo: 7, remoteAudio: 3 } }), [endpoint, roomId]);
  useEffect(() => () => { agent.close(); stop(stream); }, [agent, stream]);
  return <AgentProvider agent={agent}><RoomSession stream={stream} onLeave={onLeave} /></AgentProvider>;
}
function RemoteMedia({ track }: { track: RemoteTrack }) { const ref = useRef<HTMLMediaElement>(null); useEffect(() => { const element = ref.current; if (!element) return; const media = new MediaStream([track.media]); element.srcObject = media; void element.play().catch(() => {}); return () => { element.pause(); element.srcObject = null; }; }, [track]); return track.kind === "video" ? <video ref={ref as React.RefObject<HTMLVideoElement>} autoPlay playsInline className="h-full w-full object-contain" /> : <audio ref={ref as React.RefObject<HTMLAudioElement>} autoPlay />; }
function RoomSession({ stream, onLeave }: { stream: MediaStream; onLeave(): void }) {
  const agent = useAgent(); const [latency, setLatency] = useState<{ mode: "fixed"; minMs: number; maxMs: number }>(); const [draft, setDraft] = useState(""); const [share, setShare] = useState<MediaStream | null>(null); const { messages, reactions, sendChat, sendReaction } = useTopics(); const remote = Object.values(agent.tracks).filter((track) => track.kind === "video");
  useEffect(() => { void agent.replaceLocalTrack("camera", stream.getVideoTracks()[0] ?? null, { contentHint: "motion" }); void agent.replaceLocalTrack("microphone", stream.getAudioTracks()[0] ?? null, { contentHint: "speech" }); }, [agent, stream]);
  useEffect(() => { agent.setState(desiredState(true, ["camera", "microphone", ...(share ? ["screen"] : [])], remote.slice(0, 7).map((track, slot) => ({ slot, trackId: track.publicationId, height: slot === 0 ? 360 : 90, minHeight: slot === 0 ? 360 : 90, minFps: 15, priority: slot === 0 ? 200 : 10 })), latency)); }, [agent, latency, remote, share]);
  const startShare = async () => { try { const display = await navigator.mediaDevices.getDisplayMedia({ video: { width: { ideal: 1920 }, height: { ideal: 1080 }, frameRate: { ideal: 30 } }, audio: false, surfaceSwitching: "include" } as MediaStreamConstraints); display.getVideoTracks()[0]?.addEventListener("ended", () => setShare(null), { once: true }); setShare(display); await agent.replaceLocalTrack("screen", display.getVideoTracks()[0] ?? null, { contentHint: "detail" }); } catch { /* picker cancellation is recoverable */ } };
  useEffect(() => () => { void agent.replaceLocalTrack("screen", null, { contentHint: "detail" }); stop(share); }, [agent, share]);
  return <div className="flex h-dvh flex-col bg-background"><header className="flex items-center justify-between border-b p-3"><span>Room: {agent.participantId ?? "Connecting…"}</span><div className="flex gap-2"><select aria-label="Latency mode" onChange={(event) => { const value = event.target.value; if (value === "Smooth") setLatency({ mode: "fixed", minMs: 400, maxMs: 800 }); if (value === "Balanced") setLatency({ mode: "fixed", minMs: 100, maxMs: 200 }); if (value === "Zero-latency") setLatency({ mode: "fixed", minMs: 0, maxMs: 0 }); }}><option>Auto</option><option>Smooth</option><option>Balanced</option><option>Zero-latency</option></select><Button onClick={() => share ? setShare(null) : void startShare()}>{share ? "Stop share" : "Share"}</Button><Button onClick={agent.reconnect}>Reconnect</Button><Button variant="destructive" onClick={onLeave}>End</Button></div></header>{agent.failure && <p role="alert" className="p-2 text-destructive">{agent.failure.message}</p>}<main className="meet-room-main flex min-h-0 flex-1"><section className="meet-spotlight relative flex min-h-0 flex-1 items-center justify-center bg-black"><LocalVideo stream={stream} mirror className="h-full w-full object-contain" />{reactions.map((reaction) => <span key={reaction.id} className="absolute text-4xl">{reaction.emoji}</span>)}<div className="absolute bottom-3 flex gap-2"><Button onClick={() => void agent.setLocalMuted("microphone", true)}>Mute</Button><Button onClick={() => void agent.setLocalMuted("microphone", false)}>Unmute</Button>{["👍", "❤️", "😂", "😮", "👏", "🔥"].map((emoji) => <Button key={emoji} onClick={() => sendReaction(emoji)}>{emoji}</Button>)}</div></section><aside className="meet-participants flex shrink-0 flex-col">{remote.map((track) => <RemoteMedia key={track.publicationId} track={track} />)}</aside><aside className="w-72 border-l p-3"><div className="h-full overflow-auto">{messages.map((message) => <p key={message.id}><b>{message.self ? "You" : message.sender}:</b> {message.text}</p>)}</div><form onSubmit={(event) => { event.preventDefault(); sendChat(draft); setDraft(""); }} className="flex gap-2"><Input value={draft} onChange={(event) => setDraft(event.target.value)} /><Button type="submit">Send</Button></form></aside></main></div>;
}
