// @generated by protobuf-ts 2.10.0
// @generated from protobuf file "sfu.proto" (package "sfu", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message sfu.ClientMessage
 */
export interface ClientMessage {
    /**
     * @generated from protobuf oneof: message
     */
    message: {
        oneofKind: "offer";
        /**
         * client is always impolite
         *
         * @generated from protobuf field: string offer = 1;
         */
        offer: string;
    } | {
        oneofKind: "answer";
        /**
         * @generated from protobuf field: string answer = 2;
         */
        answer: string;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message sfu.ServerMessage
 */
export interface ServerMessage {
    /**
     * @generated from protobuf oneof: message
     */
    message: {
        oneofKind: "offer";
        /**
         * @generated from protobuf field: string offer = 1;
         */
        offer: string;
    } | {
        oneofKind: "answer";
        /**
         * @generated from protobuf field: string answer = 2;
         */
        answer: string;
    } | {
        oneofKind: undefined;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class ClientMessage$Type extends MessageType<ClientMessage> {
    constructor() {
        super("sfu.ClientMessage", [
            { no: 1, name: "offer", kind: "scalar", oneof: "message", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "answer", kind: "scalar", oneof: "message", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ClientMessage>): ClientMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ClientMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClientMessage): ClientMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string offer */ 1:
                    message.message = {
                        oneofKind: "offer",
                        offer: reader.string()
                    };
                    break;
                case /* string answer */ 2:
                    message.message = {
                        oneofKind: "answer",
                        answer: reader.string()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClientMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string offer = 1; */
        if (message.message.oneofKind === "offer")
            writer.tag(1, WireType.LengthDelimited).string(message.message.offer);
        /* string answer = 2; */
        if (message.message.oneofKind === "answer")
            writer.tag(2, WireType.LengthDelimited).string(message.message.answer);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sfu.ClientMessage
 */
export const ClientMessage = new ClientMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerMessage$Type extends MessageType<ServerMessage> {
    constructor() {
        super("sfu.ServerMessage", [
            { no: 1, name: "offer", kind: "scalar", oneof: "message", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "answer", kind: "scalar", oneof: "message", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ServerMessage>): ServerMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ServerMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerMessage): ServerMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string offer */ 1:
                    message.message = {
                        oneofKind: "offer",
                        offer: reader.string()
                    };
                    break;
                case /* string answer */ 2:
                    message.message = {
                        oneofKind: "answer",
                        answer: reader.string()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string offer = 1; */
        if (message.message.oneofKind === "offer")
            writer.tag(1, WireType.LengthDelimited).string(message.message.offer);
        /* string answer = 2; */
        if (message.message.oneofKind === "answer")
            writer.tag(2, WireType.LengthDelimited).string(message.message.answer);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sfu.ServerMessage
 */
export const ServerMessage = new ServerMessage$Type();
