[package]
name = "pulsebeam-routing"
license = "AGPL-3.0"
publish = false

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
zerocopy = { version = "0.8.56", features = ["derive"] }

[dev-dependencies]
base32 = "0.5.1"
