[package]
name = "pulsebeam-agent-web"
license = "Apache-2.0"
publish = false
version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
default = ["browser"]
browser = [
    "dep:js-sys",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "dep:web-sys",
]
protocol = ["pulsebeam-agent-core/protocol"]
e2ee = ["browser", "pulsebeam-agent-core/e2ee"]

[dependencies]
pulsebeam-agent-core = { path = "../pulsebeam-agent-core" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { version = "0.3.85", optional = true }
wasm-bindgen = { version = "0.2.108", optional = true }
wasm-bindgen-futures = { version = "0.4.58", optional = true }
web-sys = { version = "0.3.85", optional = true, features = [
    "Blob",
    "Headers",
    "MessageChannel",
    "MessageEvent",
    "MessagePort",
    "Performance",
    "Request",
    "RequestInit",
    "Response",
    "Url",
    "Worker",
    "Window",
] }

[dev-dependencies]
futures-lite = { workspace = true }
pulsebeam-proto = { path = "../pulsebeam-proto" }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.58"
