[package]
name = "pulsebeam-agent-core"
license = "Apache-2.0"
publish = false
version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
default = []
protocol = ["dep:pulsebeam-proto"]
e2ee = ["dep:aes-gcm", "dep:hkdf", "dep:sha2"]

[dependencies]
aes-gcm = { workspace = true, optional = true }
hkdf = { workspace = true, optional = true }
pulsebeam-proto = { path = "../pulsebeam-proto", optional = true }
sha2 = { workspace = true, optional = true }
