[package]
name = "pulsebeam-agent-core"
license = "Apache-2.0"
publish = false
version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
aws-lc-rs = "1.16.3"
pulsebeam-proto = { path = "../pulsebeam-proto" }
