[package]
name = "pulsebeam-agent-core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
log = { version = "0.4", default-features = false }
thiserror = { version = "2.0.20", default-features = false }
pulsebeam-proto.workspace = true
uniffi = { version = "=0.32.0", default-features = false }

[lints]
workspace = true
