import { useEffect, useRef, useState } from "react";
import { useAgent } from "@pulsebeam/react";

const encoder = new TextEncoder(); const decoder = new TextDecoder();
export function useTopics() {
  const { subscribeEvents, sendTopic, participantId } = useAgent(); const [messages, setMessages] = useState<{ id: string; sender: string; text: string; self: boolean }[]>([]); const [reactions, setReactions] = useState<{ id: string; emoji: string }[]>([]); const timers = useRef(new Map<string, ReturnType<typeof setTimeout>>());
  useEffect(() => { const unsubscribe = subscribeEvents((event) => { if (event.type !== "topic-message") return; try { const data = JSON.parse(decoder.decode(event.payload)) as { id?: string; sender: string; text?: string; emoji?: string; ts: number }; const text = data.text; const emoji = data.emoji; if (event.topic === "chat" && event.mode === "ordered" && text) setMessages((old) => old.some((message) => message.id === `${event.publisherId}-${event.streamId}-${event.sequence}`) ? old : [...old, { id: `${event.publisherId}-${event.streamId}-${event.sequence}`, sender: data.sender, text, self: false }]); if (event.topic === "reactions" && emoji) { const id = data.id ?? `${event.publisherId}-${data.ts}`; setReactions((old) => old.some((reaction) => reaction.id === id) ? old : [...old, { id, emoji }]); if (!timers.current.has(id)) timers.current.set(id, setTimeout(() => { timers.current.delete(id); setReactions((old) => old.filter((reaction) => reaction.id !== id)); }, 3000)); } } catch { /* malformed payload */ } }); return () => { unsubscribe(); for (const timer of timers.current.values()) clearTimeout(timer); timers.current.clear(); }; }, [subscribeEvents]);
  return { participantId, messages, reactions, sendChat(text: string) { const trimmed = text.trim(); if (!trimmed || !participantId) return; const ts = Date.now(); sendTopic("chat", "ordered", encoder.encode(JSON.stringify({ sender: participantId, text: trimmed, ts }))); setMessages((old) => [...old, { id: `self-${ts}`, sender: participantId, text: trimmed, self: true }]); }, sendReaction(emoji: string) { if (!participantId) return; const ts = Date.now(); const id = `${participantId}-${ts}`; sendTopic("reactions", "latest", encoder.encode(JSON.stringify({ id, emoji, sender: participantId, ts }))); setReactions((old) => [...old, { id, emoji }]); timers.current.set(id, setTimeout(() => setReactions((old) => old.filter((reaction) => reaction.id !== id)), 3000)); } };
}
