// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(oneof = "client_message::Message", tags = "1")]
    pub message: ::core::option::Option<client_message::Message>,
}
/// Nested message and enum types in `ClientMessage`.
pub mod client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        /// client is always impolite
        #[prost(message, tag = "1")]
        Offer(super::RenegotiationOffer),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMessage {
    #[prost(oneof = "server_message::Message", tags = "1, 2")]
    pub message: ::core::option::Option<server_message::Message>,
}
/// Nested message and enum types in `ServerMessage`.
pub mod server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Offer(super::RenegotiationOffer),
        #[prost(message, tag = "2")]
        Answer(super::RenegotiationAnswer),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenegotiationOffer {
    #[prost(string, tag = "1")]
    pub sdp: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenegotiationAnswer {
    #[prost(string, tag = "1")]
    pub sdp: ::prost::alloc::string::String,
}
