[package]
name = "pulsebeam-rtc"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
dcsctp = "=0.1.14"
is = { git = "https://github.com/PulseBeamDev/str0m.git", branch = "patch/0.23.1", default-features = false }
str0m = { git = "https://github.com/PulseBeamDev/str0m.git", branch = "patch/0.23.1", default-features = false, features = ["aws-lc-rs"] }

[dev-dependencies]
proptest = "1.11.0"

[lints]
workspace = true
