[package]
name = "pulsebeam-agent-browser-test"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dev-dependencies]
anyhow = "1"
thirtyfour = { version = "0.37.5", default-features = false, features = ["bidi", "component", "manager", "reqwest", "rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "process"] }
