[package]
name = "pulsebeam-agent-native"
license = "Apache-2.0"
publish = false
version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
default = ["protocol"]
protocol = ["pulsebeam-agent-core/protocol"]
e2ee = ["protocol", "pulsebeam-agent-core/e2ee"]
sim = ["pulsebeam-core/sim"]

[dependencies]
pulsebeam-agent-core = { path = "../pulsebeam-agent-core" }
bytes = { workspace = true }
pulsebeam-core = { path = "../pulsebeam-core", features = ["str0m"] }
pulsebeam-proto = { path = "../pulsebeam-proto" }
str0m = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
