version: "3.8"

services:
  pulsebeam:
    image: ghcr.io/pulsebeamdev/pulsebeam:pulsebeam-v0.2.5
    restart: unless-stopped
    network_mode: "host" # Linux only; uses real host IPs for WebRTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  caddy:
    image: docker.io/library/caddy:2
    restart: unless-stopped
    network_mode: "host" # shares host networking
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    configs:
      - source: inline_caddyfile
        target: /etc/caddy/Caddyfile

configs:
  inline_caddyfile:
    content: |
      demo.pulsebeam.dev {
          reverse_proxy localhost:3000
      }

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
