version: "3.8"
services:
  pulsebeam:
    image: ghcr.io/pulsebeamdev/pulsebeam:pulsebeam-v0.2.5
    restart: unless-stopped
    network_mode: "host" # Linux only; uses real host IPs for WebRTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:

  caddy:
    image: docker.io/library/caddy:2
    restart: unless-stopped
    network_mode: "host" # shares host networking
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z # Mount the Caddyfile from the host
      - caddy_data:/data
      - caddy_config:/config
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    environment:
      - CADDY_ADMIN=0.0.0.0:2019 # Expose Caddy admin API for monitoring (optional)

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
