[package]
name = "pulsebeam-agent"
license = "Apache-2.0"
publish = false
version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true


[lints]
workspace = true

[features]
default = ["pulsebeam-agent-native/default"]
sim = ["pulsebeam-agent-native/sim"]

[dependencies]
pulsebeam-agent-native = { path = "../../agents/pulsebeam-agent-native", default-features = false }
