# Generated by //tools:update-rust-pins. Do not edit.
CARGO_METADATA_INPUTS = [
    "//crates/pulsebeam:cargo_metadata_inputs",
    "//crates/pulsebeam-cli:cargo_metadata_inputs",
    "//crates/pulsebeam-auth:cargo_metadata_inputs",
    "//crates/pulsebeam-core:cargo_metadata_inputs",
    "//crates/pulsebeam-proto:cargo_metadata_inputs",
    "//crates/pulsebeam-routing:cargo_metadata_inputs",
    "//crates/pulsebeam-rtc:cargo_metadata_inputs",
    "//crates/pulsebeam-runtime:cargo_metadata_inputs",
    "//crates/pulsebeam-simulator:cargo_metadata_inputs",
    "//crates/pulsebeam-testdata:cargo_metadata_inputs",
    "//agents/pulsebeam-agent-core:cargo_metadata_inputs",
    "//agents/pulsebeam-agent-web:cargo_metadata_inputs",
    "//agents/pulsebeam-agent-native:cargo_metadata_inputs",
    "//tools/rust/wasm_proof:cargo_metadata_inputs",
    "//sdks/rust:cargo_metadata_inputs",
    "//sdks/auth:cargo_metadata_inputs"
]
