set shell := ["bash", "-euc"]

dev: prepare
    pnpm run dev

build: prepare
    pnpm run build

check: prepare
    pnpm run check

test-fast:
    @:

test-slow:
    @:

prepare:
    pnpm install --frozen-lockfile --ignore-scripts
