[package]
name = "pulsebeam-rtc-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
pulsebeam-rtc = { path = ".." }

[[bin]]
name = "negotiate"
path = "fuzz_targets/negotiate.rs"
test = false
doc = false
bench = false

[workspace]
