name: Docker
permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches: ["main"]
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#standard-github-hosted-runners-for-public-repositories
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm64

    runs-on: ${{ matrix.runner }}

    env:
      IMAGE_NAME: ghcr.io/pulsebeamdev/pulsebeam
      IMAGE_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push native platform
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
